# Generated by Django 4.2.2 on 2023-07-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
