# Generated by Django 4.2.2 on 2023-07-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_date_created_task_date_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_expire',
        ),
    ]
